# Generated by Django 5.0.6 on 2024-07-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_itemupdated_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUserConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemGotBid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemupdated')),
                ('userPlacedABid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
        ),
    ]
