# Generated by Django 5.0.6 on 2024-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_itemuserconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuserconnect',
            name='bidAdmin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
