# Generated by Django 5.0.6 on 2024-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_itemuserconnect_bidadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuserconnect',
            name='bidAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
