# Generated by Django 5.0.6 on 2024-07-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_finishbids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishbids',
            name='user',
        ),
        migrations.AddField(
            model_name='finishbids',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bought_bids', to='shop.user'),
        ),
        migrations.AddField(
            model_name='finishbids',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sold_bids', to='shop.user'),
        ),
    ]
